/*
 * CAboutDialog.java
 *
 * Created on den 12 april 2006, 21:24
 */

package se.navitech.adempiere.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author  daniel
 */
public class CAboutDialog extends JDialog {
    /**
	 * 
	 */
	private static final long serialVersionUID = -1060559348437255480L;

	/** Creates new form CAboutDialog */
    public CAboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new JPanel();
        mainPanel = new JPanel();
        imagePanel = new JPanel();
        imageLabel = new JLabel();
        textPanel = new JPanel();
        closeButton = new JButton();
        moreTextPanel = new JPanel();
        row1Label = new JLabel();
        row2Label = new JLabel();
        row3Label = new JLabel();
        row4Label = new JLabel();
        row5Label = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));

        imageLabel.setIcon(new ImageIcon(getClass().getResource("/se/navitech/adempiere/icons/navitech_logo.jpg"))); // NOI18N
        imagePanel.add(imageLabel);

        mainPanel.add(imagePanel);

        textPanel.setBackground(new java.awt.Color(255, 255, 255));

        closeButton.setText("Close");
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        moreTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        moreTextPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 8));

        row1Label.setHorizontalAlignment(SwingConstants.CENTER);
        row1Label.setText("proudly presents");
        moreTextPanel.add(row1Label);

        row2Label.setFont(new java.awt.Font("Tahoma", 1, 11));
        row2Label.setHorizontalAlignment(SwingConstants.CENTER);
        row2Label.setText("The iDempiere Account Editor");
        moreTextPanel.add(row2Label);

        row3Label.setHorizontalAlignment(SwingConstants.CENTER);
        row3Label.setText("Author: Daniel Tamm");
        moreTextPanel.add(row3Label);

        row4Label.setHorizontalAlignment(SwingConstants.CENTER);
        row4Label.setText("http://www.navitech.se/sv/adempiere");
        moreTextPanel.add(row4Label);

        row5Label.setHorizontalAlignment(SwingConstants.CENTER);
        row5Label.setText("Version 1.2");
        moreTextPanel.add(row5Label);

        org.jdesktop.layout.GroupLayout textPanelLayout = new org.jdesktop.layout.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moreTextPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, textPanelLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textPanelLayout.createSequentialGroup()
                .add(moreTextPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );

        mainPanel.add(textPanel);

        backPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-369)/2, (screenSize.height-370)/2, 369, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel backPanel;
    private JButton closeButton;
    private JLabel imageLabel;
    private JPanel imagePanel;
    private JPanel mainPanel;
    private JPanel moreTextPanel;
    private JLabel row1Label;
    private JLabel row2Label;
    private JLabel row3Label;
    private JLabel row4Label;
    private JLabel row5Label;
    private JPanel textPanel;
    // End of variables declaration//GEN-END:variables
    
}
