/*
 * CAboutDialog.java
 *
 * Created on den 12 april 2006, 21:24
 */

package se.navitech.adempiere.gui;

/**
 *
 * @author  daniel
 */
public class CAboutDialog extends javax.swing.JDialog {
    
    /** Creates new form CAboutDialog */
    public CAboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        backPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        moreTextPanel = new javax.swing.JPanel();
        row1Label = new javax.swing.JLabel();
        row2Label = new javax.swing.JLabel();
        row3Label = new javax.swing.JLabel();
        row4Label = new javax.swing.JLabel();
        row5Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        backPanel.setLayout(new java.awt.BorderLayout());

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/navitech/adempiere/icons/navitech_logo.jpg")));
        imagePanel.add(imageLabel);

        mainPanel.add(imagePanel);

        textPanel.setBackground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        moreTextPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 8));

        moreTextPanel.setBackground(new java.awt.Color(255, 255, 255));
        row1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        row1Label.setText("proudly presents");
        moreTextPanel.add(row1Label);

        row2Label.setFont(new java.awt.Font("Tahoma", 1, 11));
        row2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        row2Label.setText("The Adempiere Account Editor");
        moreTextPanel.add(row2Label);

        row3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        row3Label.setText("Author: Daniel Norin");
        moreTextPanel.add(row3Label);

        row4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        row4Label.setText("http://www.navitech.se/sv/adempiere");
        moreTextPanel.add(row4Label);

        row5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        row5Label.setText("Version 1.0");
        moreTextPanel.add(row5Label);

        org.jdesktop.layout.GroupLayout textPanelLayout = new org.jdesktop.layout.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(moreTextPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, textPanelLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textPanelLayout.createSequentialGroup()
                .add(moreTextPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );
        mainPanel.add(textPanel);

        backPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-369)/2, (screenSize.height-370)/2, 369, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel moreTextPanel;
    private javax.swing.JLabel row1Label;
    private javax.swing.JLabel row2Label;
    private javax.swing.JLabel row3Label;
    private javax.swing.JLabel row4Label;
    private javax.swing.JLabel row5Label;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables
    
}
