/*
 * CAdempiereAcctEdit.java
 *
 * Created on den 31 december 2005, 16:40
 */

package se.navitech.adempiere.gui;

import java.io.*;
import java.util.*;
import se.navitech.adempiere.CDefaultAccount;

/**
 *
 * @author  Daniel Norin
 */
public class CAdempiereAcctEdit extends javax.swing.JFrame {

    private static File    m_currentDirectory;
    
    private static final String PROPSFILENAME="compiereAcctEdit.properties";
    
    private static Properties m_globalProps;
    
    private TreeMap<String, CDefaultAccount>  m_defaultAccounts;
    
    /**
     * Creates new form CAdempiereAcctEdit
     */
    public CAdempiereAcctEdit() {
        initComponents();
        
        /** Load default accounts from file */
        loadDefaultAccounts();
        
        // See if we have a properties file
        File propsFile = new File(System.getProperty("user.home") + File.separator + PROPSFILENAME);
        m_globalProps = new Properties();
        if (propsFile.exists()) {
            try {
                // Read the properties
                m_globalProps.loadFromXML(new BufferedInputStream(new FileInputStream(propsFile)));
            } catch (Exception e) {
                e.printStackTrace(System.err);
            }
        } else {
            System.out.println("Didn't find " + propsFile.getAbsolutePath());
        }
        
        // Get current directory from properties
        String currentDir = m_globalProps.getProperty("defaultDirectory");
        if (currentDir!=null) {
            m_currentDirectory = new File(currentDir);
        } else {
            m_currentDirectory = new File(System.getProperty("user.home"));
        }
        
    }
    
    public static File  getCurrentDirectory() {
        return(m_currentDirectory);
    }
    
    /**
     * Loads default accounts into a tree map
     */
    private void loadDefaultAccounts() {
        
        Properties props = new Properties();
        try {
            props.load(ClassLoader.getSystemResourceAsStream("default_accounts.properties"));
            // Put the properties in the tree map
            m_defaultAccounts = new TreeMap<String, CDefaultAccount>();
            String key;
            for (Iterator it = props.keySet().iterator(); it.hasNext(); ) {
                key = (String)it.next();
                m_defaultAccounts.put(key, new CDefaultAccount(key, props.getProperty(key)));
            }
        } catch (Exception e) {
            e.printStackTrace(System.err);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        fileMenuSeparator = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adempiere Account Editor");
        setName("compiereAcctEditMain");
        desktopPane.setBackground(new java.awt.Color(0, 0, 153));
        desktopPane.setOpaque(false);
        desktopPane.setPreferredSize(new java.awt.Dimension(450, 300));
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");
        newFileMenuItem.setMnemonic('n');
        newFileMenuItem.setText("New schema file");
        newFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(newFileMenuItem);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open Schema File");
        openMenuItem.setToolTipText("Open Schema File");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(openMenuItem);

        fileMenu.add(fileMenuSeparator);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });

        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-923)/2, (screenSize.height-725)/2, 923, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        CAboutDialog aboutDialog = new CAboutDialog(this, true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void newFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileMenuItemActionPerformed
        newSchemaFile();
    }//GEN-LAST:event_newFileMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        openSchemaFile();
    }//GEN-LAST:event_openMenuItemActionPerformed
    
    /**
     * Create a blank schema file
     */
    public void newSchemaFile() {
        
        CSchemaFileMainFrame schemaFileFrame = new CSchemaFileMainFrame(null, m_defaultAccounts);
        schemaFileFrame.setVisible(true);
        desktopPane.add(schemaFileFrame);
        // TODO: Make automatic location
        schemaFileFrame.setLocation(0,0);
        try {
            schemaFileFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace(System.err);
        }
        
    }
    
    /**
     * Lets the user select a file to open
     */
    private void openSchemaFile() {
        
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        if (m_currentDirectory!=null) {
            fc.setCurrentDirectory(m_currentDirectory);
        }
        fc.setDialogTitle("Choose Schema File to open");
        int result = fc.showOpenDialog(this);
        if (result==fc.APPROVE_OPTION) {
            // Set the current directory
            m_currentDirectory = fc.getCurrentDirectory();
            // Open the file
            CSchemaFileMainFrame schemaFileFrame = new CSchemaFileMainFrame(fc.getSelectedFile(), m_defaultAccounts);
            schemaFileFrame.setVisible(true);
            desktopPane.add(schemaFileFrame);
            // TODO: Make automatic location
            schemaFileFrame.setLocation(0,0);
            try {
                schemaFileFrame.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {}
        }
        
    }
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        
        // Save properties file
        try {
            // Save current directory
            m_globalProps.setProperty("defaultDirectory", m_currentDirectory.getAbsolutePath());
            m_globalProps.storeToXML(new BufferedOutputStream(new java.io.FileOutputStream(System.getProperty("user.home") + File.separator + PROPSFILENAME)), null);
        } catch (Exception e) {
            e.printStackTrace(System.err);
        }
        
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAdempiereAcctEdit().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JSeparator fileMenuSeparator;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newFileMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables
    
}
