/*
 * CNewAccountDialog.java
 *
 * Created on den 25 februari 2006, 10:22
 */

package se.navitech.adempiere.gui;

import javax.swing.*;

/**
 *
 * @author  Daniel Norin
 */
public class CNewAccountDialog extends javax.swing.JDialog {

    private boolean m_isOk = false;
    
    /** Creates new form CNewAccountDialog */
    public CNewAccountDialog(java.awt.Frame parent, String parentAccountId) {
        super(parent, true);
        initComponents();
        parentAcctText.setText(parentAccountId);
        accountIdText.setText(parentAccountId);
        accountIdText.requestFocus();
        getRootPane().setDefaultButton(createButton);
    }
    
    public String getAccountId() {
        return(accountIdText.getText().trim());
    }
    
    public String getAccountName() {
        return(accountText.getText().trim());
    }
    
    public String getParentAccountId() {
        return(parentAcctText.getText());
    }
    
    public boolean isSummaryAccount() {
        return(summaryCheck.isSelected());
    }
    
    public boolean isOk() {
        return(m_isOk);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        accountIdLabel = new javax.swing.JLabel();
        accountIdText = new javax.swing.JTextField();
        accountName = new javax.swing.JLabel();
        accountText = new javax.swing.JTextField();
        parentAcctLabel = new javax.swing.JLabel();
        parentAcctText = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        summaryCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create new account");
        accountIdLabel.setText("Account id");

        accountName.setText("Account name");

        parentAcctLabel.setText("Parent acct");

        parentAcctText.setEditable(false);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        summaryCheck.setText("Summary account");
        summaryCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        summaryCheck.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(66, 66, 66)
                        .add(createButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(accountIdLabel)
                            .add(accountName)
                            .add(parentAcctLabel))
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(parentAcctText)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, accountIdText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, accountText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, summaryCheck))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(accountIdLabel)
                    .add(accountIdText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(accountName)
                    .add(accountText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(summaryCheck)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(parentAcctLabel)
                    .add(parentAcctText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(createButton))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed

        // Make sure there is something filled in
        if (getAccountId().length()==0) {
            JOptionPane.showMessageDialog(null, "Account id can't be empty.");
            accountIdText.requestFocus();
            return;
        }
        
        if (getAccountName().length()==0) {
            JOptionPane.showMessageDialog(null, "Account name can't be empty.");
            accountText.requestFocus();
            return;
        }
        if (getAccountId()!=null && getAccountId().equals(getParentAccountId())) {
            JOptionPane.showMessageDialog(null, "Account id can't be the same as parent account id.");
            return;
        }
        
        m_isOk = true;
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_createButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JTextField accountIdText;
    private javax.swing.JLabel accountName;
    private javax.swing.JTextField accountText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel parentAcctLabel;
    private javax.swing.JTextField parentAcctText;
    private javax.swing.JCheckBox summaryCheck;
    // End of variables declaration//GEN-END:variables
    
}
